# Generated by Django 4.0.4 on 2022-05-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainful', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
